[project]
name = "text-utilities-mcp"
version = "1.0.0"
description = "Text Utilities MCP Server for Puch AI"
dependencies = [
    "mcp>=1.0.0",
    "pydantic>=2.0.0", 
    "python-dotenv>=1.0.0",
]
requires-python = ">=3.8"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"